services:
  nginx-proxy:
    build: .
    ports:
      - 80:80
    volumes:
     - ./templates:/etc/nginx/templates
     - ./www:/usr/share/nginx/html
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
